version: "3.9"

services:
  app:
    build:
      context: .           # referring current directory
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >             # docker run override if not provided below command will execute
      sh -c "python manage.py runserver 0.0.0.0:8000"